### PR TITLE
Move 5Zig Website to Jekyll-based setup

### PR DESCRIPTION
**Pull request by Andre601**
## New Website Design!
Oh boy this took a while...
I started working on this like what... 5 months ago?

Anyway, I now feel comfortable to present a first working version of the new and improved 5Zig Reborn Website!

## Changes

- Moved Website to a Jekyll-based setup.
  - This allows us to use Markdown files with some extra spicy stuff (YAML Frontmatter, include blocks, etc) for styling instead of HTML.
  - Theme is [Minimal Mistakes](https://github.com/mmistakes/minimal-mistakes) by @mmistakes
- Moved all necessary pages to either `_pages` or `_changelogs` (for changelogs... duh)
- Moved all the files into a `site` folder for cleaner repository (Please read below section)
- Added Button to download Cape-Templates from the downloads page. Note that the link won't work on the page-preview due to how relative links work.

## Breaking changes
I made some breaking changes which will require this repository to update in some specific ways.

First of all did I setup files in such a way that they are located within a `site` directory.
Next did I create a workflow, which would push any changes made on the `development` branch - which needs to be created first - to the master branch using a gh-pages push action.

I now suggest to create a `development` branch and make it the new default branch.
You can then tell GitHub to keep using `master` as the branch for publishing the website.

Next will you also need to uncomment the `cname` option in the workflow, as it would otherwise not provide a CNAME file when pushing changes, making you lose the 5zigreborn.eu domain.

## Known issues/Limitations

- Patreon Button isn't integrated into the pages (Not sure how to implement it in an easy way. Any ideas?)

## Things left to do

- [x] Move all relevant pages
  - [x] Home (Main Page) [[Done](https://www.andre601.ch/5zig-reborn.github.io/)]
  - [x] Downloads [[Done](https://www.andre601.ch/5zig-reborn.github.io/downloads/)]
  - [x] FAQ [[Done](https://www.andre601.ch/5zig-reborn.github.io/faq/)]
  - [x] Changelogs [[Done](https://www.andre601.ch/5zig-reborn.github.io/changelogs/)]
- [x] Update old images on Front page. Also make them same size [Done]
- [x] Add "Not affiliated" notice to footer [Done]
- [x] ~~Add more buttons to front-page [Maybe. You unfortunately can't change their style]~~
  Not needed. Most links are in the footer.

## Live-Preview
A live-preview can be found here: https://andre601.ch/5zig-reborn.github.io

### CODE REVIEW

**Comment by roccodev** [comment]
I'll clone this locally in the following days, but in the meantime please change 5Zig to 5zig.

**Comment by Andre601** [comment]
> I'll clone this locally in the following days, but in the meantime please change 5Zig to 5zig.

Done

**Comment by Andre601** [comment]
I consider the page pretty much done.
The Download buttons work and only things left imo are the remaining images for chat and plugins preview and adding the patreon somewhere...

**Comment by Andre601** [comment]
I've added the Patreon button to the footer since it looks shit on the top (Or at least I can't really squeeze it into the nav section to work)

But the position is still not perfect sadly enough...

**Comment by Andre601** [comment]
Decided to remove the patreon button, simply because it can't really fit anywhere and the footer links to it already.

I see this PR as ready now, so feel free to suggest changes or just give feedback

**Comment by Andre601** [comment]
Just also a small remonder that this PR should only be merged once a development branch was made, and the target of this PR was altered to it.

**Comment by roccodev** [comment]
LGTM. Jekyll wasn't able to compile it locally, but it looks fine on the deployed version here (<https://andre601.github.io/5zig-reborn.github.io>).

**Pull request merged**
